name: build
on:
    push:
        paths:
            # Source
            - src/**
            # Workflow
            - .github/workflows/build.yaml
            # TypeScript
            - tsconfig*
            # Depdendencies
            - package.json
            - yarn.lock
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Latest Commit
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  fetch-depth: 1

            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  registry-url: 'https://registry.npmjs.org'

            - name: Restore Dependencies
              uses: actions/cache@v2
              id: dependency-cache
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install Dependencies
              # if: steps.dependency-cache.outputs.cache-hit != 'true'
              run: yarn install

            - name: Lint
              run: yarn lint

            - name: Format
              run: yarn format

            - name: Spelling
              run: yarn spelling

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test

            - name: Publish
              if: startsWith(github.ref, 'refs/tags/')
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
