name: build
on:
    push:
        branches:
            - 'master'
        paths:
            # Source
            - src/**
            # Workflow
            - .github/workflows/build.yaml
            # TypeScript
            - tsconfig*
            # Dependencies
            - package.json
            - yarn.lock
    pull_request:
        paths:
            # Source
            - src/**
            # Workflow
            - .github/workflows/build.yaml
            # TypeScript
            - tsconfig*
            # Dependencies
            - package.json
            - yarn.lock

jobs:
    build:
        runs-on: ${{ matrix.os }}
        container: ${{ matrix.container }}
        env:
            CXX: clang++
            CC: clang
        strategy:
            fail-fast: false
            matrix:
                include:
                    # Linux (GLIBC)
                    - os: ubuntu-20.04
                      container: ubuntu:20.04
                      nodejs_version: 12
                      prebuild: true
                    - os: ubuntu-20.04
                      container: ubuntu:20.04
                      nodejs_version: 14
                    - os: ubuntu-20.04
                      container: ubuntu:20.04
                      nodejs_version: 16
                      checks: true
                    # Linux (MUSL)
                    - os: ubuntu-20.04
                      container: node:12-alpine3.12
                      prebuild: true
                    - os: ubuntu-20.04
                      container: node:14-alpine3.13
                    - os: ubuntu-20.04
                      container: node:16-alpine3.13
                    # MacOS
                    - os: macos-10.15
                      nodejs_version: 12
                      prebuild: true
                    - os: macos-10.15
                      nodejs_version: 14
                    - os: macos-10.15
                      nodejs_version: 16
                    # Windows
                    - os: windows-2019
                      nodejs_version: 12
                      prebuild: true
                    - os: windows-2019
                      nodejs_version: 14
                    - os: windows-2019
                      nodejs_version: 16

        steps:
            # Linux (GLIBC) Dependencies
            - name: Dependencies (Linux/GLIBC)
              if: contains(matrix.container, 'ubuntu')
              run: |
                  apt-get update -y
                  apt-get upgrade -y
                  apt-get install -y curl build-essential clang cmake make git python3
                  curl -fsSL https://deb.nodesource.com/setup_${{ matrix.nodejs_version }}.x | bash -
                  apt-get install -y nodejs
                  npm install --global yarn
              env:
                  DEBIAN_FRONTEND: noninteractive
            # Linux (MUSL) Dependencies
            - name: Dependencies (Linux/MUSL)
              if: contains(matrix.container, 'alpine')
              run: |
                  apk add build-base cmake make git python3 --update-cache
                  npm install --global yarn --force
            # Windows / MacOS Dependencies
            - name: Dependencies (macOS, Windows)
              if: contains(matrix.os, 'macos') || contains(matrix.os, 'windows')
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.nodejs_version }}

            - name: Checkout Latest Commit
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  fetch-depth: 1

            - name: CHOWN Container Volume
              if: matrix.container
              run: chown root.root .

            - name: Install Dependencies
              run: yarn install

            - name: Lint
              if: matrix.checks
              run: yarn lint

            - name: Format
              if: matrix.checks
              run: yarn format

            - name: Spelling
              if: matrix.checks
              run: yarn spelling

            - name: Build
              run: |
                  yarn build:ts
                  yarn build:cpp

            - name: Test
              run: yarn test

            - name: Prebuild
              if: github.ref == 'refs/heads/master' && matrix.prebuild
              run: |
                  yarn prebuild --upload "${{ secrets.GITHUB_TOKEN }}"

            - name: Publish
              if: github.ref == 'refs/heads/master'
              uses: pascalgn/npm-publish-action@1.3.7
              with:
                  commit_pattern: "^v(\\d+\\.\\d+\\.\\d+\\S*)$"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
