name: build
on:
    push:
        paths:
            # Source
            - src/**
            # Workflow
            - .github/workflows/build.yaml
            # TypeScript
            - tsconfig*
            # Dependencies
            - package.json
            - yarn.lock
    pull_request:
        paths:
            # Source
            - src/**
            # Workflow
            - .github/workflows/build.yaml
            # TypeScript
            - tsconfig*
            # Dependencies
            - package.json
            - yarn.lock

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Latest Commit
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  fetch-depth: 1

            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  registry-url: 'https://registry.npmjs.org'

            - name: Restore Dependencies
              uses: actions/cache@v2
              id: dependency-cache
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install Dependencies
              run: yarn install

            - name: Lint
              run: yarn lint

            - name: Format
              run: yarn format

            - name: Spelling
              run: yarn spelling

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test

            - name: Publish
              if: github.ref == 'refs/heads/master'
              uses: pascalgn/npm-publish-action@1.3.7
              with:
                  commit_pattern: "^v(\\d+\\.\\d+\\.\\d+\\S*)$"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
