name: format
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    prettier:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2

            - name: Git Diff
              id: diff
              run: |
                  if [ $GITHUB_BASE_REF ]; then
                      # Pull Request
                      export FETCH_TARGET="$GITHUB_BASE_REF"
                      export DIFF_TARGET="origin/$GITHUB_BASE_REF"
                  else
                      # Push
                      export FETCH_TARGET="${{ github.event.before }}"
                      export DIFF_TARGET="${{ github.event.before }}"
                  fi
                  git fetch origin $FETCH_TARGET --depth=1
                  export DIFF=$(git diff --diff-filter=ACMR --name-only $DIFF_TARGET $GITHUB_SHA | grep -E --line-buffered "\.([jt]sx?|json|md|yaml)$")
                  echo "$DIFF"
                  export CLEAN_DIFF=$(echo "$DIFF" | sed -e 's/^/.\//' | sed ':a;N;$!ba;s/\n/ /g')
                  echo "::set-output name=diff::$CLEAN_DIFF"
                  echo "::set-output name=has_diffs::$(test -n "$DIFF" && echo true || echo false)"

            - name: Add Yarn to $PATH
              id: yarn-cache-dir-path
              run: |
                  yarn config set prefix $(yarn cache dir)
                  echo $(yarn global bin) >> $GITHUB_PATH
                  yarn config set global-folder $(yarn cache dir)
                  echo "::set-output name=dir::$(yarn cache dir)"

            - name: Restore Prettier
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  key: ${{ runner.os }}-prettier
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}

            - name: Install Prettier
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn global add prettier

            - name: Run Prettier
              if: steps.diff.outputs.has_diffs == 'true'
              run: prettier --list-different ${{ steps.diff.outputs.diff }}
